config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'posts#index'
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  resources :reports, only: %i[index edit update destroy]

  resources :comments, only: %i[edit update destroy] do
    member do
      put :like, to: 'comments#vote'
    end
    resources :reports, only: %i[new create]
    resources :comments, only: %i[new create]
  end

  resources :posts do
    member do
      put :like, to: 'posts#vote'
      get :new_suggestion, to: 'comments#new_suggestion'
      get :suggestions, to: 'posts#suggestions'
    end
    resources :reports, only: %i[new create]
    resources :comments, only: %i[create]
  end

  resources :dashboard, only: [:index]

  get :user_report, to: 'dashboard#user_report'
  get :user_suggestions, to: 'dashboard#user_suggestions'

  resources :moderators, only: [:index]

  get :publish, to: 'moderators#publish'
  get :unpublish, to: 'moderators#unpublish'

  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index show]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index
    @user = params[:user] || current_user.id
    @user = @user.to_i
    @posts = Post.includes(:user).where(user_id: @user).order(created_at: :desc)
  end

  def user_report
    @reports = current_user.reports
  end

  def user_suggestions
    @suggestions = current_user.comments.where(suggestion: true).order(created_at: :desc)
  end
end

app/views/dashboard/index.html.erb
<h1>User Dashboard</h1>
<% if @user == current_user.id %>
  <div class = "row mb-3 justify-content-center text-center">
    <div class = "border border-secondary w-50 m-1 p-2">
      <i class="fa fa-user-secret fa-5x" aria-hidden="true"></i>
      <br>
      <%= current_user.name.upcase_first %>
      <br>
      <%= link_to "Profile", edit_user_registration_path, type: "button", class: "btn btn-light border" %>
      <%= link_to "My Report", user_report_path, type: "button", class: "btn btn-light border" %>
      <%= link_to "My Suggestions", user_suggestions_path, type: "button", class: "btn btn-light border" %>
    </div>
  </div>
<% end %>

<%= render @posts, page: "post-index" %>

app/views/dashboard/user_report.html.erb
<%= render partial: 'posts/previous_page' %>

<h1>User Reports</h1><hr>
<%= render "reports/report_table", reports: @reports %>

app/views/dashboard/user_suggestions.html.erb
<%= render partial: 'posts/previous_page' %>

<% @suggestions.each do |suggestion| %>
<div id = "comments-section">
  <div class = "container">
    <div class = "row">
     <div class="media border mb-1 ml-5 p-2 w-100 rounded">
        <div class="media-body">
          <h4 class="media-heading title"><%= suggestion.user.name %></h4>
          <hr>
          <%= link_to 'View Post', suggestion.commentable %>
          <p class="comment-body">
            <%= suggestion.content.html_safe %><br>
            <div id = "comment-buttons">
              <% if delete_btn?(suggestion, suggestion.commentable) %>
                <b> | </b>
                <%= link_to 'Delete', suggestion, class: 'crud-link', method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
              <% end %>
              <% if suggestion.commentable_type == "Post" %>
                <b> | </b>
                <%= link_to "reply", new_comment_comment_path(suggestion), remote: true, class: 'crud-link'%>
              <% end %>
            </div>
          </p>
          <div id = 'comment_<%= suggestion.id %>_reply' style = 'display: none'><h3>loading failed</h3></div>
        </div>
      </div>
    </div>
  </div>
</div>

<% end %>