config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'posts#index'
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  resources :reports, only: %i[index edit update destroy]

  resources :comments, only: %i[edit update destroy] do
    member do
      put :like, to: 'comments#vote'
    end
    resources :reports, only: %i[new create]
    resources :comments, only: %i[new create]
  end

  resources :posts do
    member do
      put :like, to: 'posts#vote'
      get :new_suggestion, to: 'comments#new_suggestion'
      get :suggestions, to: 'posts#suggestions'
    end
    resources :reports, only: %i[new create]
    resources :comments, only: %i[create]
  end

  resources :dashboard, only: [:index]

  get :user_report, to: 'dashboard#user_report'
  get :user_suggestions, to: 'dashboard#user_suggestions'

  resources :moderators, only: [:index]

  get :publish, to: 'moderators#publish'
  get :unpublish, to: 'moderators#unpublish'

  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index show]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :content, presence: true

  acts_as_votable # association for like gem "act_as_votable"
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_comment, only: %i[destroy edit update vote]
  before_action :find_commentable, only: %i[create edit new]
  respond_to :js, :json, :html

  def edit
    authorize @comment
  end

  def update
    authorize @comment
    if @comment.update(comment_params)
      update_page
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @comment = Comment.new
    @toggle = true
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    authorize @comment, policy_class: CommentPolicy
    if @comment.save
      create_page
    else
      render :create, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @comment
    @comment.destroy

    render inline: '$("#comments-section").load(location.href+" #comments-section>*","");'
  end

  def vote
    if !current_user.liked? @comment
      @comment.liked_by current_user
    elsif current_user.liked? @comment
      @comment.unliked_by current_user
    end
  end

  def new_suggestion
    @comment = Comment.new
    @commentable = Post.find(params[:id])
  end

  private

  def update_page
    record = @comment.commentable
    case record.class.name
    when 'Post'
      redirect_to record, notice: 'comment updated.'
    when 'Comment'
      record = record.commentable
      redirect_to record, notice: 'comment updated.'
    end
  end

  def create_page
    respond_to do |format|
      case @comment.commentable_type
      when 'Post'
        format.html { redirect_to @commentable }
        format.js { render inline: '$("#comments-section").load(location.href+" #comments-section>*","");' }
      when 'Comment'
        @comment = Comment.new
        @toggle = false
        format.js { render :new }
      end
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def find_commentable
    if params[:post_id]
      @commentable = Post.find(params[:post_id])
    elsif params[:comment_id]
      @commentable = Comment.find(params[:comment_id])
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :suggestion)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  def commentable_owner?(record)
    case record.class.name
    when 'Post'
      record.user_id == current_user.id
    when 'Comment'
      record.user_id == current_user.id || record.commentable.user_id == current_user.id
    end
  end

  def suggestion_reply?(commentable)
    case commentable.class.name
    when 'Post'
      false
    when 'Comment'
      commentable.suggestion
    end
  end

  def suggestion?(suggestion, commentable)
    !suggestion && !suggestion_reply?(commentable)
  end

  def delete_btn?(comment, commentable)
    owner?(comment) || current_user.moderator? || commentable_owner?(commentable)
  end

  def edit_btn?(comment, commentable)
    owner?(comment) && !suggestion_reply?(commentable)
  end
end

app/views/comments/_comment.html.erb
<% commentable.comments.includes(:user).where( suggestion: suggestion ).order(created_at: :desc).each do |comment| %>
  <div class = "container">
    <div class = "row">
     <div class="media border mb-1 ml-5 p-2 w-100 rounded">
        <div class="media-body">
          <h4 class="media-heading title"><%= comment.user.name %></h4>
          <hr>
          <p class="comment-body">
            <%= comment.content.html_safe %><br>
            <hr>
            <% if suggestion?(suggestion, commentable) %>
              <span id = "comment_<%= comment.id %>_count"><%= pluralize(comment.cached_votes_up, "like") %></span>
              <hr>
            <% end %>
            <div id = "comment-buttons">
              <% if suggestion?(suggestion, commentable) %>
                <%= link_to like_comment_path(comment), id: "comment_#{comment.id}_btn", class: (current_user.liked? comment) ? 'like-btn liked' : 'like-btn', method: :put, remote: :true do %>
                  <i class = 'fa fa-thumbs-up'> Like</i>
                <% end %>

                <% if !owner?(comment) %>
                  <b> | </b>
                  <% if reported?(comment) %>
                    <% report_id = find_report(comment).ids%>
                    <div class="btn-group">
                      <a class="crud-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Reported
                      </a>
                      <div class="dropdown-menu">
                        <%= link_to 'Edit Report', edit_report_path(:id => report_id), class: 'dropdown-item' %>
                        <%= link_to 'Delete Report', report_path(:id => report_id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'dropdown-item' %>
                      </div>
                    </div>
                  <% else %>
                    <%= link_to 'Report', new_comment_report_path(:comment_id => comment.id), class: 'crud-link' %>
                  <% end %>
                <% end %>
              <% end %>

              <% if delete_btn?(comment, commentable) %>
                <b> | </b>
                <%= link_to 'Delete', comment, class: 'crud-link', method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
              <% end %>

              <% if edit_btn?(comment, commentable) %>
                <b> | </b>
                <%= link_to 'Edit', edit_comment_path(comment), class: 'crud-link' %>
              <% end %>
              <% if comment.commentable_type == "Post" %>
                <b> | </b>
                <%= link_to "reply", new_comment_comment_path(comment), remote: true, class: 'crud-link'%>
              <% end %>
            </div>
          </p>
          <div id = 'comment_<%= comment.id %>_reply' style = 'display: none'><h3>loading failed</h3></div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_comment_section.html.erb
<%= render partial: "comments/form", locals: {commentable: commentable, comment: comment, id: id}%>
<hr>
<%= render partial: "comments/comment", locals: {commentable: commentable, suggestion: false} %>

app/views/comments/_form.html.erb
<%= form_for [commentable, comment], id: id, namespace: id, remote: true do |form|%>
  <div class="field">
    <%= form.trix_editor :content, required: true %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
if(!$('#error_explanation').length){
  $('#comments-section').prepend(`<div id="error_explanation"></div> `);
}
<% if @comment.errors.any? %>
  $('#error_explanation').html(`
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  `);
<% else %>
  $('#error_explanation').html(`
    <h2>Unknown Error Occured</h2>
    <ul>
      <li>Failed to save comment.</li>
    </ul>
  `);
<% end %>

app/views/comments/edit.html.erb
<%= render partial: 'posts/previous_page' %>

<h1>Editing Comment</h1>

<%= render 'form', commentable: @commentable, comment: @comment, id: 'edit' %>

app/views/comments/new.js.erb
if(!$('#comment_<%= @commentable.id %>_reply').is(':visible') || <%= !@toggle %>){
  $('#comment_<%= @commentable.id %>_reply').html(`
    <hr><div id="reply" class="ml-5"><h3>Reply</h3><br>
      <%= render partial: "comments/comment_section", locals: {commentable: @commentable, comment: @comment, id: "comment_#{@commentable.id}"}%>
    </div>
  `);
}
if( <%= @toggle %> ){
  $('#comment_<%= @commentable.id %>_reply').toggle();
}

app/views/comments/new_suggestion.html.erb
<%= render partial: 'posts/previous_page' %>

<h3>Suggestion</h3>
<%= form_for [@commentable, @comment] do |form|%>
  <div class="field">
    <%= form.trix_editor :content, required: true %>
  </div>
  <div class="field">
    <%= form.hidden_field :suggestion, value: true %>
  </div>
  <div class="actions">
    <%= form.submit "Create Suggestion" %>
  </div>
<% end %>

app/views/comments/vote.js.erb
<% if current_user.liked? @comment %>
  $("#comment_<%= @comment.id %>_btn").addClass('liked')
<% else %>
  $("#comment_<%= @comment.id %>_btn").removeClass('liked')
<% end %>
$("#comment_<%= @comment.id %>_count").html("<%= pluralize(@comment.cached_votes_up, "like") %>")