config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'posts#index'
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  resources :reports, only: %i[index edit update destroy]

  resources :comments, only: %i[edit update destroy] do
    member do
      put :like, to: 'comments#vote'
    end
    resources :reports, only: %i[new create]
    resources :comments, only: %i[new create]
  end

  resources :posts do
    member do
      put :like, to: 'posts#vote'
      get :new_suggestion, to: 'comments#new_suggestion'
      get :suggestions, to: 'posts#suggestions'
    end
    resources :reports, only: %i[new create]
    resources :comments, only: %i[create]
  end

  resources :dashboard, only: [:index]

  get :user_report, to: 'dashboard#user_report'
  get :user_suggestions, to: 'dashboard#user_suggestions'

  resources :moderators, only: [:index]

  get :publish, to: 'moderators#publish'
  get :unpublish, to: 'moderators#unpublish'

  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index show]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :content, :title, presence: true
  validates :title, length: { maximum: 100 }

  enum status: {
    pending: 0,
    published: 1
  }

  acts_as_votable # association for like gem "act_as_votable"
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy
end

app/controllers/api/v1/posts_controller.rb
# frozen_string_literal: true

class Api::V1::PostsController < ApplicationController
  before_action :set_post, only: [:show]
  skip_before_action :authenticate_user!

  def index
    @posts = Post.published.includes(:user).order(created_at: :desc)
    render json: @posts
  end

  def show
    if @post
      render json: @post
    else
      render json: @post.errors
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy vote suggestions]
  respond_to :js, :json, :html

  def index
    @posts = Post.published.includes(:user).order(created_at: :desc)
  end

  def show; end

  def suggestions; end

  def new
    @post = current_user.posts.build
  end

  def edit
    authorize @post
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to post_url(@post), notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_url(@post), notice: 'Post was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @post
    @post.destroy

    redirect_back fallback_location: root_path, notice: 'Post was successfully destroyed.'
  end

  def vote
    authorize @post
    if !current_user.liked? @post
      @post.liked_by current_user
    elsif current_user.liked? @post
      @post.unliked_by current_user
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def suggestion_btn?(page, post)
    page != 'post-suggestions' && owner?(post)
  end

  def post_delete_btn?(post)
    owner?(post) || current_user.moderator?
  end

  def show_comments?(page, post)
    page == 'post-show' && post.published?
  end
end

app/views/posts/_back.html.erb
<%= link_to 'javascript:history.back()' do%>
  <i class="fa fa-arrow-left"> Back</i>
<% end %>
<br><br>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= trix_editor :post, :content, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class = "mb-3 p-2 border border-secondary">
  <article>
    <div class = <%= page %>>
      <h3><%= post.title %></h3>
      <% if suggestion_btn?(page, post) %>
        <%= link_to "suggestions", suggestions_post_path(post) %>
      <% end %>
      <ul class="post-meta list-inline">
          <li class="list-inline-item">
              <i class="fa fa-user-circle-o"></i> <%= link_to post.user.name, dashboard_index_path(:user => post.user) %>
          </li>
          <b>/&nbsp</b>
          <li class="list-inline-item">
              <i class="fa fa-calendar-o"></i> <%= I18n.l(post.created_at, format: :long) %>
          </li>
      </ul>
      <p><%= post.content.html_safe %></p>
    </div>

    <hr>

    <span id = "post_<%= post.id %>_count"><%= pluralize(post.cached_votes_up, "like") %></span>

    <br><br>

    <% if page != "post-show" %>
      <button type="button" class="btn btn-light"><%= link_to 'Show', post %></button>
    <% end %>

    <% if post.published? %>
      <%= link_to like_post_path(post), id: "post_#{post.id}_btn", class: (current_user.liked? post) ? 'like-btn liked' : 'like-btn', method: :put, remote: :true do %>
        <i class = 'fa fa-thumbs-up'> Like</i>
      <% end %>
      <% if !owner?(post) %>
        <% if reported?(post) %>
          <% report_id =  find_report(post).ids%>
          <div class="btn-group">
            <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Reported
            </button>
            <div class="dropdown-menu">
              <%= link_to 'Edit Report', edit_report_path(:id => report_id), class: 'dropdown-item' %>
              <%= link_to 'Delete Report', report_path(:id => report_id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'dropdown-item' %>
            </div>
          </div>
        <% else %>
          <button type="button" class="btn btn-warning"><%= link_to 'Report', new_post_report_path(:post_id => post.id) %></button>
        <% end %>

        <button type="button" class="btn btn-light"><%= link_to 'Suggestion', new_suggestion_post_path(post) %></button>
      <% end %>

    <% end %>

    <% if owner?(post) %>
      <button type="button" class="btn btn-light"><%= link_to 'Edit', edit_post_path(post) %></button>
    <% end %>

    <% if current_user.moderator? %>
      <% if post.pending? %>
       <button type="button" class="btn btn-light"><%= link_to 'Publish', publish_path(:post => post) %></button>
      <% elsif post.published? %>
        <button type="button" class="btn btn-danger"><%= link_to 'Unpublish', unpublish_path(:post => post) %></button>
      <% end %>
    <% end %>

    <% if post_delete_btn?(post) %>
      <button type="button" class="btn btn-danger"><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></button>
    <% end %>
  </article>
  <% if show_comments?(page, post) %>
    <hr>
    <h3>Add Comments</h3><br>
    <div id = 'comments-section'>
      <%= render partial: "comments/comment_section", locals: {commentable: post, comment: Comment.new, id: "post_#{post.id}"}%>
    </div>
  <% end %>
  <% if page == "post-suggestions" %>
    <br><hr>
    <h3>Suggestions</h3>
    <div id = 'comments-section' >
      <%= render partial: "comments/comment", locals: {commentable: post, suggestion: true}%>
    </div>
  <% end %>
</div>

app/views/posts/_previous_page.html.erb
<%= link_to 'javascript:history.back()' do%>
  <i class="fa fa-arrow-left"> Back</i>
<% end %>
<br><br>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class = "d-flex justify-content-center">
  <button class = "btn btn-light border">
    <%= link_to 'New Post', new_post_path %>
  </button>
</div>
<hr>
<h1>Recent Posts</h1>

<%= render @posts, page: "post-index" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render partial: 'posts/previous_page' %>

<%= render @post, page: "post-show" %>

app/views/posts/suggestions.html.erb
<%= render partial: 'posts/previous_page' %>

<%= render @post, page: "post-suggestions" %>

app/views/posts/vote.js.erb
<% if current_user.liked? @post %>
  $("#post_<%= @post.id %>_btn").addClass('liked');
<% else %>
  $("#post_<%= @post.id %>_btn").removeClass('liked');
<% end %>
$("#post_<%= @post.id %>_count").html("<%= pluralize(@post.cached_votes_up, "like") %>")