config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'posts#index'
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  resources :reports, only: %i[index edit update destroy]

  resources :comments, only: %i[edit update destroy] do
    member do
      put :like, to: 'comments#vote'
    end
    resources :reports, only: %i[new create]
    resources :comments, only: %i[new create]
  end

  resources :posts do
    member do
      put :like, to: 'posts#vote'
      get :new_suggestion, to: 'comments#new_suggestion'
      get :suggestions, to: 'posts#suggestions'
    end
    resources :reports, only: %i[new create]
    resources :comments, only: %i[create]
  end

  resources :dashboard, only: [:index]

  get :user_report, to: 'dashboard#user_report'
  get :user_suggestions, to: 'dashboard#user_suggestions'

  resources :moderators, only: [:index]

  get :publish, to: 'moderators#publish'
  get :unpublish, to: 'moderators#unpublish'

  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index show]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/posts">BlogApp</a>
    </div>
    <% if current_user %>
      <ul class="nav navbar-nav">
        <li class = "navbar-item"><%= link_to "Home",  posts_path, class: 'nav-link'%></li>
        <% if current_user.moderator? %>
          <li class = "navbar-item"><%= link_to "Moderator-Panel", moderators_path, class: 'nav-link' %></li>
        <% elsif current_user.admin? %>
          <li class = "navbar-item"><%= link_to "Admin-Panel", '/admin', class: 'nav-link' %></li>
        <% end %>
        <li class = "navbar-item"><%= link_to "Profile", dashboard_index_path, class: 'nav-link' %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class = "navbar-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
      </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li class = "navbar-item"><%= link_to "Login", new_user_session_path, class: 'nav-link' %></li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>